<a href="https://colab.research.google.com/github/xMichaelz/Modelos1-2025-2-CompetenciaKaggle/blob/main/01_exploraci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
datos = pd.read_csv("/content/train.csv", sep=",")
# Display de dataset
train = pd.DataFrame(datos)
train.head()

,ID,PERIODO_ACADEMICO,E_PRGM_ACADEMICO,E_PRGM_DEPARTAMENTO,E_VALORMATRICULAUNIVERSIDAD,E_HORASSEMANATRABAJA,F_ESTRATOVIVIENDA,F_TIENEINTERNET,F_EDUCACIONPADRE,F_TIENELAVADORA,...,E_PRIVADO_LIBERTAD,E_PAGOMATRICULAPROPIO,F_TIENECOMPUTADOR,F_TIENEINTERNET.1,F_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,INDICADOR_1,INDICADOR_2,INDICADOR_3,INDICADOR_4
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383889 entries, 0 to 383888
Data columns (total 21 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ID                           383889 non-null  int64
 1   PERIODO_ACADEMICO            383889 non-null  int64
 2   E_PRGM_ACADEMICO             383889 non-null  object
 3   E_PRGM_DEPARTAMENTO          383889 non-null  object
 4   E_VALORMATRICULAUNIVERSIDAD  380404 non-null  object
 5   E_HORASSEMANATRABAJA         366781 non-null  object
 6   F_ESTRATOVIVIENDA            366149 non-null  object
 7   F_TIENEINTERNET              369195 non-null  object
 8   F_EDUCACIONPADRE             371057 non-null  object
 9   F_TIENELAVADORA              361875 non-null  object
 10  F_TIENEAUTOMOVIL             359736 non-null  object
 11  E_PRIVADO_LIBERTAD           383888 non-null  object
 12  E_PAGOMATRICULAPROPIO        380279 non-null  object
 13  F_TIENECOMPUTADOR            362807 non-null  object
 14  F_TIENEINTERNET.1            369194 non-null  object
 15  F_EDUCACIONMADRE             370811 non-null  object
 16  RENDIMIENTO_GLOBAL           383888 non-null  object
 17  INDICADOR_1                  383888 non-null  float64
 18  INDICADOR_2                  383888 non-null  float64
 19  INDICADOR_3                  383888 non-null  float64
 20  INDICADOR_4                  383888 non-null  float64
dtypes: float64(4), int64(2), object(15)
memory usage: 61.5+ MB

In [ ]:
train['E_PRGM_ACADEMICO'].unique()

array(['ENFERMERIA', 'DERECHO', 'MERCADEO Y PUBLICIDAD',
       'ADMINISTRACION DE EMPRESAS', 'PSICOLOGIA', 'MEDICINA VETERINARIA',
       'INGENIERIA MECANICA', 'ADMINISTRACIÓN EN SALUD OCUPACIONAL',
       'INGENIERIA INDUSTRIAL', 'ADMINISTRACIÓN FINANCIERA',
       'HOTELERIA Y TURISMO', 'LICENCIATURA EN CIENCIAS SOCIALES',
       'LICENCIATURA EN PEDAGOGIA INFANTIL', 'COMUNICACION SOCIAL',
       'CIENCIA POLITICA',
       'PROFESIONAL EN GESTIÓN DE LA SEGURIDAD Y LA SALUD LABORAL',
       'MAESTRO EN MÚSICA', 'INGENIERIA MECATRONICA', 'TRABAJO SOCIAL',
       'LICENCIATURA EN BIOLOGIA Y EDUCACION AMBIENTAL',
       'INGENIERIA CIVIL', 'CONTADURIA PÚBLICA',
       'ADMINISTRACION EN SALUD', 'ADMINISTRACIÓN DE EMPRESAS',
       'ESTADISTICA', 'LICENCIATURA EN BIOLOGIA',
       'INGENIERIA AGROINDUSTRIAL', 'ZOOTECNIA',
       'COMUNICACION AUDIOVISUAL',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN HUMANIDADES-INGLES',
       'COMUNICACION SOCIAL  - PERIODISMO',
       'SEGURIDAD Y SALUD EN EL TRABAJO', 'MEDICINA',
       'ADMINISTRACION DE LA SEGURIDAD SOCIAL', 'CONTADURIA PUBLICA',
       'ODONTOLOGIA', 'DISEÑO INDUSTRIAL', 'ECONOMIA',
       'INGENIERIA DE PROCESOS INDUSTRIALES', 'CONTADURÍA PÚBLICA',
       'INGENIERIA DE SISTEMAS', 'ARQUITECTURA',
       'LICENCIATURA EN FILOSOFÍA', 'ADMINISTRACION FINANCIERA',
       'ADMINISTRACION AMBIENTAL', 'INGENIERIA ELECTRONICA',
       'INGENIERÍA INDUSTRIAL', 'PSICOLOGÍA', 'INGENIERIA BIOMEDICA',
       'ADMINISTRACION Y DIRECCION DE EMPRESAS', 'INGENIERÍA ELECTRÓNICA',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN CIENCIAS NATURALES Y EDUCACION AMBIENTAL',
       'LICENCIATURA EN EDUCACIÓN FÍSICA, RECREACIÓN Y DEPORTE',
       'LICENCIATURA EN INGLÉS',
       'LICENCIATURA EN EDUCACION BÁSICA CON ÉNFASIS EN CIENCIAS NATURALES Y EDUCACIÓN AMBIENTAL',
       'INGENIERIA AMBIENTAL', 'NEGOCIOS INTERNACIONALES',
       'INGENIERIA  CIVIL', 'LICENCIATURA EN LENGUAS EXTRANJERAS',
       'MEDICINA VETERINARIA Y ZOOTECNIA', 'DISEÑO GRAFICO',
       'QUIMICA FARMACEUTICA',
       'LICENCIATURA EN BILINGÜISMO CON ÉNFASIS EN INGLÉS',
       'ADMINISTRACIÓN EN SEGURIDAD Y SALUD EN EL TRABAJO',
       'FINANZAS Y COMERCIO INTERNACIONAL',
       'LICENCIATURA EN EDUCACION PREESCOLAR',
       'LICENCIATURA EN PSICOLOGIA Y PEDAGOGIA',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN HUMANIDADES E IDIOMAS',
       'INGENIERIA DE CONTROL', 'RELACIONES INTERNACIONALES',
       'INGENIERIA DE TELECOMUNICACIONES', 'INSTRUMENTACION QUIRURGICA',
       'PROFESIONAL EN FINANZAS Y NEGOCIOS INTERNACIONALES',
       'DISEÑO VISUAL',
       'LICENCIATURA EN LENGUA CASTELLANA,INGLES Y FRANCES',
       'FISIOTERAPIA', 'FARMACIA', 'LICENCIATURA EN IDIOMAS EXTRANJEROS',
       'COMUNICACION Y LENGUAJES AUDIOVISUALES',
       'INGENIERIA DE DISEÑO DE PRODUCTO', 'ARTE DANZARIO',
       'COMUNICACION SOCIAL-PERIODISMO',
       'FINANZAS Y NEGOCIOS INTERNACIONALES', 'INGENIERIA QUIMICA',
       'ADMINISTRACION DEL MEDIO AMBIENTE', 'OPTOMETRIA',
       'COMUNICACION SOCIAL- PERIODISMO',
       'LICENCIATURA EN PEDAGOGÍA INFANTIL', 'INGENIERIA FINANCIERA',
       'JURISPRUDENCIA', 'INGENIERIA DE ALIMENTOS',
       'LICENCIATURA EN MATEMATICAS', 'SOCIOLOGIA',
       'INGENIERIA DE SISTEMAS Y COMPUTACION', 'PROFESIONAL EN DEPORTE',
       'ESTUDIOS LITERARIOS', 'INGENIERIA AGRONOMICA',
       'LICENCIATURA EN LENGUAS MODERNAS CON ENFASIS EN INGLES Y FRANCES',
       'ADMINISTRACION DE EMPRESAS TURISTICAS',
       'PROFESIONAL EN CINE Y TELEVISION', 'NUTRICION Y DIETETICA',
       'COMUNICACIÓN SOCIAL', 'TERAPIA RESPIRATORIA', 'FILOSOFIA',
       'LICENCIATURA EN INGLES', 'INGENIERÍA DE TELECOMUNICACIONES',
       'INGENIERIA DE PRODUCCION', 'INGENIERIA EN TELECOMUNICACIONES',
       'ADMINISTRACION DE NEGOCIOS INTERNACIONALES',
       'INGENIERÍA MULTIMEDIA', 'PROFESIONAL EN DISEÑO GRAFICO',
       'ENFERMERÍA', 'LICENCIATURA EN FILOSOFIA Y EDUCACION RELIGIOSA',
       'LICENCIATURA EN BIOLOGIA Y QUIMICA', 'INGENIERIA ELECTRICA',
       'INGENIERIA ELECTRONICA Y TELECOMUNICACIONES',
       'LICENCIATURA EN TEOLOGIA', 'INGENIERIA AGROPECUARIA',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN EDUCACION FISICA, RECREACION Y DEPORTES',
       'TERAPIA OCUPACIONAL', 'NEGOCIOS INTERNACIONALES SEGUNDO CICLO',
       'ADMINISTRACION AMBIENTAL Y DE LOS RECURSOS NATURALES',
       'INGENIERIA ADMINISTRATIVA', 'ADMINISTRACION DE LA CALIDAD',
       'ADMINISTRACION MARITIMA Y FLUVIAL', 'INGENIERIA AGROFORESTAL',
       'NEGOCIOS Y RELACIONES INTERNACIONALES', 'FILOLOGIA E IDIOMAS',
       'GERENCIA EN SISTEMAS DE INFORMACION EN SALUD', 'ECONOMÍA',
       'LICENCIATURA EN ETNOEDUCACION',
       'LICENCIATURA EN LENGUA CASTELLANA E INGLES',
       'TRADUCCION INGLES-FRANCES-ESPAÑOL',
       'GESTIÓN EN ECOLOGÍA Y TURISMO', 'INGENIERIA DE MATERIALES',
       'LICENCIATURA EN EDUCACION ARTISTICA', 'INTRUMENTACION QUIRURGICA',
       'PLANEACION Y DESARROLLO SOCIAL', 'LICENCIATURA EN ARTES',
       'INGENIERIA EN MULTIMEDIA', 'PROFESIONAL EN CRIMINALISTICA',
       'LICENCIATURA EN EDUCACION PARA LA PRIMERA INFANCIA',
       'ENTRENAMIENTO DEPORTIVO',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN MATEMATICAS',
       'LICENCIATURA EN CIENCIAS NATURALES Y EDUCACION AMBIENTAL',
       'INGENIERÍA AMBIENTAL', 'INGENIERIA DE PETROLEOS',
       'CIENCIAS DEL DEPORTE Y DE LA EDUCACION FISICA', 'BIOLOGIA',
       'INGENIERIA MULTIMEDIA',
       'LICENCIATURA EN EDUCACION FISICA, DEPORTES Y RECREACION',
       'INGENIERIA ELECTROMECANICA',
       'LICENCIATURA EN CIENCIAS DEL DEPORTE',
       'COMUNICACION SOCIAL Y PERIODISMO',
       'MERCADEO Y NEGOCIOS INTERNACIONALES',
       'ADMINISTRACION PUBLICA TERRITORIAL',
       'ADMINISTRACIÓN INTEGRAL DE RIESGOS DE SEGURIDAD Y SALUD EN EL TRABAJO',
       'ADMINISTRACION & SERVICIO',
       'LICENCIATURA EN LENGUA CASTELLANA Y COMUNICACION',
       'CIENCIAS DE LA INFORMACION Y LA DOCUMENTACION',
       'LICENCIATURA EN EDUCACIÓN BÁSICA CON ÉNFASIS EN INGLÉS',
       'COMUNICACION SOCIAL - PERIODISMO', 'CIENCIAS MILITARES',
       'LICENCIATURA EN EDUCACION FISICA Y DEPORTES',
       'INGENIERÍA DE SOFTWARE',
       'CIENCIAS NAVALES PARA OFICIALES DE INFANTERIA DE MARINA',
       'INGENIERIA DE SONIDO',
       'LICENCIATURA EN ETNOEDUCACION CON ENFASIS EN CIENCIAS SOCIALES',
       'LICENCIATURA EN EDUCACIÓN PARA LA PRIMERA INFANCIA',
       'INGENIERIA EN HIGIENE Y SEGURIDAD OCUPACIONAL',
       'ADMINISTRACION DE LA SEGURIDAD Y SALUD OCUPACIONAL',
       'ECONOMIA Y FINANZAS INTERNACIONALES', 'BACTERIOLOGIA',
       'CIENCIA POLÍTICA Y GOBIERNO',
       'COMUNICACION AUDIOVISUAL Y MULTIMEDIOS', 'MERCADEO',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN LENGUA CASTELLANA',
       'ECONOMIA Y NEGOCIOS INTERNACIONALES',
       'PROFESIONAL EN LENGUAS MODERNAS',
       'INGENIERIA SANITARIA Y AMBIENTAL',
       'LICENCIATURA EN EDUCACION INFANTIL', 'PERIODISMO',
       'PROFESIONAL EN CONTADURIA PUBLICA',
       'LICENCIATURA EN EDUCACIÓN BÁSICA PRIMARIA',
       'LINGUISTICA Y LITERATURA', 'LICENCIATURA EN EDUCACIÓN INFANTIL',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN MATEMATICA HUMANIDADES Y LENGUA CASTELLANA',
       'PROFESIONAL EN ADMINISTRACIÓN DE EMPRESAS', 'ANTROPOLOGIA',
       'INGENIERÍA DE SISTEMAS', 'AGRONOMIA',
       'ADMINISTRACION DE NEGOCIOS',
       'BACTERIOLOGIA Y LABORATORIO CLINICO', 'FONOAUDIOLOGIA',
       'LICENCIATURA EN  CIENCIAS NATURALES Y EDUCACION AMBIENTAL',
       'ADMINISTRACION Y GESTION AMBIENTAL',
       'LICENCIATURA EN ESPAÑOL Y LITERATURA',
       'PROFESIONAL EN AGRONEGOCIOS', 'LINGUISTICA',
       'INGENIERIA DE PRODUCTIVIDAD Y CALIDAD',
       'LICENCIATURA EN LENGUAS MODERNAS',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN EDUCACION FISICA,RECREACION Y DEPORTES',
       'INGENIERIA AMBIENTAL Y SANITARIA',
       'LICENCIATURA EN PEDAGOGIA  INFANTIL', 'ADMINISTRACION PUBLICA',
       'RELACIONES ECONOMICAS INTERNACIONALES',
       'ADMINISTRACION DE EMPRESAS COMERCIALES',
       'LICENCIATURA EN EDUCACIÓN BÁSICA CON ÉNFASIS EN EDUCACIÓN ARTÍSTICA',
       'LENGUAS MODERNAS', 'INGENIERIA EN TOPOGRAFIA',
       'CIENCIAS BIBLICAS',
       'LICENCIATURA EN ESPAÑOL Y LENGUAS EXTRANJERAS',
       'INGENIER¿A EN SOFTWARE', 'DISEÑO Y PRODUCCION DE MODA',
       'INGENIERIA DE MERCADOS',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN LENGUAS EXTRANJERAS',
       'ARTES PLASTICAS', 'ADMINISTRACION BANCARIA Y FINANCIERA',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN HUMANIDADES: LENGUA CASTELLANA E INGLES',
       'ADMINISTRACION DE SISTEMAS INFORMATICOS', 'INGENIERIA PESQUERA',
       'DISEÑO DE MODAS',
       'LICENCIATURA EN COMUNICACION E INFORMATICA EDUCATIVA',
       'LICENCIATURA EN EDUCACION FISICA', 'GEOLOGIA',
       'INGENIERÍA MECATRÓNICA', 'ADMINISTRACION TURISTICA Y HOTELERA',
       'LICENCIATURA EN EDUCACION CON ENFASIS EN EDUCACION ESPECIAL',
       'QUIMICA', 'PROFESIONAL EN ACTIVIDAD FISICA Y DEPORTE', 'HISTORIA',
       'MICROBIOLOGIA Y BIOANALISIS', 'ADMINISTRACIÓN TECNÓLOGICA',
       'ADMINISTRACION DE MERCADEO',
       'LICENCIATURA EN LENGUAS MODERNAS INGLES-FRANCES',
       'SALUD OCUPACIONAL', 'INGENIERÍA AMBIENTAL Y SANITARIA',
       'ECOLOGIA DE ZONAS COSTERAS', 'PROFESIONAL EN TRABAJO SOCIAL',
       'INGENIERIA AMBIENTAL Y DE SANEAMIENTO',
       'LICENCIATURA EN CIENCIAS NATURALES',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN HUMANIDADES Y LENGUA CASTELLANA',
       'CONSTRUCCION',
       'ADMINISTRACION DE EMPRESAS TURÍSTICAS Y HOTELERAS',
       'LICENCIATURA EN INGLÉS-ESPAÑOL', 'ADMINISTRACION INDUSTRIAL',
       'LICENCIATURA EN ARTES ESCENICAS CON ENFASIS EN TEATRO',
       'TEOLOGIA', 'COMERCIO Y NEGOCIOS INTERNACIONALES', 'PUBLICIDAD',
       'INGENIERIA EN AUTOMATIZACIÓN', 'OPTOMETRÍA', 'INGENIERIA FISICA',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN CIENCIAS SOCIALES',
       'LICENCIATURA EN EDUCACION  FISICA RECREACION  Y  DEPORTE',
       'CIENCIA POLITICA Y GOBIERNO',
       'LICENCIATURA EN PEDAGOGÍA SOCIAL PARA LA REHABILITACIÓN',
       'PROFESIONAL EN ENTRENAMIENTO DEPORTIVO',
       'CONSTRUCCION Y GESTION EN ARQUITECTURA', 'INGENIERÍA MECÁNICA',
       'INGENIERÍA EN DISEÑO INDUSTRIAL', 'NUTRICIÓN Y DIETÉTICA',
       'INGENIERIA FORESTAL', 'FINANZAS Y COMERCIO EXTERIOR',
       'PROFESIONAL  EN DISEÑO GRAFICO', 'ADMINISTRACION',
       'COMERCIO EXTERIOR', 'NEGOCIOS Y FINANZAS INTERNACIONALES',
       'LICENCIATURA EN LENGUA EXTRANJERA INGLES',
       'ADMINISTRACIÓN EN SALUD', 'INGENIERÍA CIVIL',
       'LICENCIATURA EN EDUCACIÓN FÍSICA Y DEPORTES',
       'LICENCIATURA EN EDUCACION BASICA ENFASIS EN EDUCACION FISICA, RECREACION Y DEPORTE',
       'ARTES PLÁSTICAS Y VISUALES', 'INGENIERIA GEOLOGICA',
       'INGENIERÍA AGRONÓMICA',
       'INGENIERIA EN SEGURIDAD INDUSTRIAL E HIGIENE OCUPACIONAL',
       'COMERCIO INTERNACIONAL Y FINANZAS',
       'INGENIERÍA GEOGRÁFICA Y AMBIENTAL',
       'FINANZAS Y RELACIONES INTERNACIONALES',
       'ADMINISTRACION COMERCIAL Y DE MERCADEO',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN HUMANIDADES -  LENGUA CASTELLANA',
       'LETRAS - FILOLOGIA HISPANICA',
       'LICENCIATURA EN MATEMATICAS Y ESTADISTICA', 'CINE',
       'INGENIERIA INFORMATICA', 'INGENIERIA DE MINAS Y METALURGIA',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN INGLES',
       'ADMINISTRACION POLICIAL', 'ADMINISTRACION DE SERVICIOS DE SALUD',
       'PROFESIONAL EN MARKETING Y NEGOCIOS INTERNACIONALES',
       'LICENCIATURA EN ARTES PLASTICAS', 'ADMINISTRACION DEPORTIVA',
       'COMUNICACION SOCIAL -  PERIODISMO',
       'ADMINISTRACION EN FINANZAS Y NEGOCIOS INTERNACIONALES',
       'INGENIERIA AGROECOLOGICA', 'INGENIERIA GEOGRAFICA Y AMBIENTAL',
       'INGENIERÍA ELECTROMECÁNICA',
       'LICENCIATURA EN EDUCACION FISICA,RECREACION Y DEPORTES',
       'ADMINISTRACIÓN COMERCIAL',
       'LICENCIATURA EN INFORMATICA Y MEDIOS AUDIOVISUALES',
       'LICENCIATURA EN EDUCACION FISICA RECREACION Y DEPORTE',
       'DERECHO Y CIENCIAS POLITICAS',
       'ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES',
       'INGENIERIA DE TRANSPORTE Y VIAS', 'DEPORTE Y ACTIVIDAD FISICA',
       'CULINARIA Y GASTRONOMÍA', 'INGENIERIA DE SISTEMAS E INFORMATICA',
       'LICENCIATURA  PEDAGOGIA INFANTIL',
       'PROFESIONAL EN MERCADEO Y PUBLICIDAD', 'BIOINGENIERIA',
       'LICENCIATURA EN IDIOMAS MODERNOS ESPAÑOL- INGLES',
       'COMUNICACION SOCIALY PERIODISMO', 'ARQUEOLOGIA',
       'ADMINISTRACION HUMANA', 'CRIMINALISTICA', 'DISEÑO',
       'GESTION EMPRESARIAL', 'DANZA',
       'LICENCIATURA EN LENGUA CASTELLANA Y LITERATURA',
       'LICENCIATURA EN ARTES ESCENICAS',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN EDUCACION FISICA,RECREACION Y DEPORTE',
       'LICENCIATURA EN ARTES VISUALES', 'ARCHIVISTICA',
       'CIENCIAS POLÍTICAS', 'DEPORTE',
       'ADMINISTRACION DE EMPRESAS  Y  GESTION AMBIENTAL', 'TEOLOGÍA',
       'LICENCIATURA EN PREESCOLAR',
       'INGENIERIA DE SISTEMAS Y TELECOMUNICACIONES',
       'CULTURA FISICA, DEPORTE Y RECREACION',
       'INGENIERÍA EN INFORMÁTICA', 'INGENIERÍA ELÉCTRICA',
       'HISTORIA Y ARCHIVISTICA', 'LICENCIATURA EN INFORMATICA',
       'GESTION Y DESARROLLO URBANOS',
       'LICENCIATURA EN CULTURA, FISICA, RECREACION Y DEPORTES',
       'DISEÑO GRÁFICO', 'CONSTRUCCIONES CIVILES', 'GASTRONOMIA',
       'MATEMATICAS', 'BIOLOGÍA', 'COMUNICACION GRAFICA PUBLICITARIA',
       'LICENCIATURA EN FISICA',
       'INGENIERIA EN HIGIENE Y SEGURIDAD INDUSTRIAL',
       'ADMINISTRACIÓN DE EMPRESAS TURÍSTICAS Y HOTELERAS',
       'COMUNICACIÓN Y ENTRETENIMIENTO DIGITAL', 'INGENIERIA EN SOFTWARE',
       'LICENCIATURA EN LENGUAS EXTRANJERAS: INGLES-FRANCES',
       'LICENCIATURA EN MATEMATICAS Y FISICA',
       'LICENCIATURA EN DISEÑO TECNOLOGICO CON ENFASIS EN SISTEMAS MECANICOS',
       'ADMINISTRACIÓN DE EMPRESAS TURÍSTICAS',
       'PROGRAMA PROFESIONAL UNIVERSITARIO EN LENGUAS EXTRANJERAS',
       'ADMINISTRACI¿N LOG¿STICA',
       'SISTEMAS DE INFORMACION Y DOCUMENTACION',
       'DISEÑO DE LA COMUNICACION GRAFICA', 'FILOSOFIA Y LETRAS',
       'LICENCIATURA EN LENGUAS EXTRANJERAS INGLES-FRANCES',
       'DISEÑO VISUAL DIGITAL', 'INGENIERIA DE MINAS',
       'CULTURA FISICA Y DEPORTE',
       'LICENCIATURA EN EDUCACION ARTISTICA CON ENFASIS EN DANZA Y TEATRO',
       'LICENCIATURA EN LENGUAS EXTRANJERAS CON ÉNFASIS EN INGLÉS',
       'INGENIERIA AERONAUTICA', 'INGENIERIA EN ENERGIA',
       'INGENIERIA AGRICOLA', 'ESPAÑOL Y FILOLOGIA CLASICA',
       'ARTES VISUALES',
       'ADMINISTRACION EN SALUD: ENFASIS EN GESTION DE SERVICIOS DE SALUD Y  ENFASIS EN GESTION SANITARIA Y AMBIENTAL',
       'LICENCIATURA EN EDUCACI¿N ART¿STICA',
       'LICENCIATURA EN EDUCACIÓN BÁSICA CON ÉNFASIS EN HUMANIDADES- LENGUA CASTELLANA',
       'FORMACION MUSICAL',
       'LICENCIATURA EN EDUCACIÓN BÁSICA CON ÉNFASIS EN HUMANIDADES, LENGUA CASTELLANA',
       'ADMINISTRACION DE SISTEMAS INFORMÁTICOS',
       'LICENCIATURA EN EDUCACIÓN BÁSICA, CON ÉNFASIS EN HUMANIDADES, LENGUA CASTELLANA',
       'DIRECCION Y PRODUCCION DE MEDIOS AUDIOVISUALES',
       'ADMINISTRACIÓN PÚBLICA',
       'PROFESIONAL EN NEGOCIOS INTERNACIONALES',
       'DISEÑO DIGITAL Y MULTIMEDIA',
       'GEOGRAFIA APLICADA A LA ORGANIZACION DEL ESPACIO Y PLANIFICACION REGIONAL',
       'INGENIERIA EN MECATRONICA',
       'INGENIERÍA EN DISEÑO DE ENTRETENIMIENTO DIGITAL', 'FISICA',
       'INGENIERIA EN TELEMATICA', 'LICENCIATURA EN MUSICA',
       'INGENIERIA FINANCIERA Y DE NEGOCIOS', 'MICROBIOLOGIA',
       'PROFESIONAL EN PSICOLOGÍA',
       'LICENCIATURA EN EDUCACIÓN BÁSICA CON ÉNFASIS EN CIENCIAS SOCIALES',
       'DISEÑO DE COMUNICACION VISUAL', 'ADMINISTRACION AGROPECUARIA',
       'ADMINISTRACIÓN LOGISTICA', 'LICENCIATURA EN LENGUA CASTELLANA',
       'INGENIERÍA EN ENERGÍA', 'INGENIERÌA INFORMÀTICA',
       'INGENIERIA DE LA CALIDAD', 'INGENIERÍA AERONÁUTICA',
       'COMERCIO INTERNACIONAL',
       'LICENCIATURA EN EDUCACION FISICA, RECREACION Y DEPORTES',
       'ADMINISTRACIÓN DE SERVICIOS DE SALUD',
       'LICENCIATURA EN HUMANIDADES Y LENGUA CASTELLANA',
       'ADMINISTRACION AERONAUTICA', 'TURISMO',
       'CIENCIAS MILITARES AERONÁUTICAS', 'CIENCIAS DEL DEPORTE',
       'LICENCIATURA EN PEDAGOG¿A INFANTIL',
       'MERCADEO NACIONAL E INTERNACIONAL', 'QUIMICA INDUSTRIAL',
       'RELACIONES INTERNACIONALES Y ESTUDIOS POLITICOS',
       'LICENCIATURA EN EDUCACION ESPECIAL',
       'LICENCIATURA EN EDUCACION POPULAR',
       'PROFESIONAL EN DISEÑO INDUSTRIAL', 'COMUNICACION Y PERIODISMO',
       'BIBLIOTECOLOGIA', 'ADMINISTRACIÓN DE COMERCIO EXTERIOR',
       'FILOSOFÍA', '3°  CICLO PROFESIONAL NEGOCIOS INTERNACIONALES',
       'LICENCIATURA EN CIENCIAS RELIGIOSAS', 'INGENIERIA DE SOFTWARE',
       'LICENCIATURA EN HUMANIDADES, LENGUA CASTELLANA E INGLES',
       'ADMINISTRACION DE EMPRESAS AGROPECUARIAS',
       'PRODUCCION AGROINDUSTRIAL', 'DISEÑO DE MEDIOS  INTERACTIVOS',
       'LICENCIATURA EN MATEMÁTICAS',
       'CIENCIA DE LA INFORMACION Y BIBLIOTECOLOGIA',
       'LICENCIATURA EN PEDAGOGIA DE LA PRIMERA INFANCIA',
       'LICENCIATURA EN EDUCACION AMBIENTAL',
       'INGENIERIA EN SEGURIDAD Y SALUD PARA EL TRABAJO',
       'LICENCIATURA EN LENGUAS  EXTRANJERAS',
       'LICENCIATURA EN EDUCACION RELIGIOSA', 'CONTADURÍA PÚBLICA.',
       'INGENIERÍA BIOQUÍMICA',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN INFORMATICA',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN HUMANIDADES, ESPAÑOL Y LENGUAS EXTRANJERAS',
       'LICENCIATURA EN TECNOLOGIA E INFORMATICA', 'ARTES ESCÉNICAS',
       'ESTUDIOS MUSICALES', 'ADMINISTRACIÓN TURÍSTICA Y HOTELERA',
       'INGENIERIA DE PROCESOS', 'INGENIERÍA DE PRODUCCIÓN',
       'MATEMÁTICA APLICADA',
       'LICENCIATURA EN BIOLOGIA CON ENFASIS EN EDUCACION AMBIENTAL',
       'ADMINISTRACIÓN LOGÍSTICA', 'DISE¿¿O DE COMUNICACI¿¿N GR¿¿FICA',
       'ADMINISTRACION DE EMPRESAS TURISTICAS Y HOTELERAS',
       'LICENCIATURA EN FILOSOFIA Y LENGUA CASTELLANA', 'MUSICA',
       'ADMINISTRACION DE INSTITUCIONES DE SERVICIO',
       'PUBLICIDAD Y MERCADEO', 'ARTES DE LA ESCENA', 'DISEÑO INTERIOR',
       'CONSTRUCCION EN ARQUITECTURA E INGENIERIA',
       'CINE Y COMUNICACIÓN DIGITAL', 'LICENCIATURA  EN MATEMATICAS',
       'LICENCIATURA EN EDUCACION FISICA,RECREACION Y DEPORTE',
       'HISTORIA Y PATRIMONIO', 'LITERATURA',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN EDUCACION ARTISTICA',
       'LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN HUMANIDADES,LENGUA CASTELLANA E INGLES',
       'GEOGRAFIA', 'BIOLOGIA APLICADA',
       'GERENCIA DE LA SEGURIDAD Y ANALISIS SOCIO POLITICO',
       'LICENCIATURA EN EDUCACIÓN ESPECIAL',
       'LICENCIATURA EN INGLÉS COMO LENGUA EXTRANJERA',
       'LICENCIATURA EN EDUCACION ARTISTICA Y ARTES ESCENICAS',
       'INGENIERIA METALURGICA', 'LICENCIATURA EN FILOSOFIA',
       'CINE Y TELEVISION', 'INGENIERIA SANITARIA',
       'LICENCIATURA EN INGLES - ESPAÑOL', 'INGENIERÍA FORESTAL',
       'INGENIERIA EN CONTROL', 'COMUNICACION AUDIOVISUAL Y MULTIMEDIAL',
       'FINANZAS', 'ARTES DE LA GRABACION Y PRODUCCION MUSICAL',
       'LICENCIATURA EN LINGUISTICA Y LITERATURA',
       'LICENCIATURA EN EDUCACION ARTISTICA Y CULTURAL',
       'INGENIERÍA DE LAS ARTES DIGITALES',
       'PROFESIONAL UNIVERSITARIO EN FOTOGRAFÍA PARA MEDIOS',
       'COMUNICACION PUBLICITARIA',
       'CIENCIAS DE LA COMPUTACIÓN E INTELIGENCIA ARTIFICIAL',
       'COMUNICACION SOCIAL     Y     PERIODISMO',
       'LICENCIATURA EN EDUCACION BASICA  CON ENFASIS EN HUMANIDADES Y LENGUA CASTELLANA',
       'ECOLOGIA', 'ADMINISTRACIÓN DE LA SALUD OCUPACIONAL',
       'LICENCIATURA EN INGLÉS Y BILINGÜISMO', 'CIENCIAS POLITICAS',
       'GOBIERNO Y RELACIONES INTERNACIONALES',
       'ADMINISTRACIÓN DE EMPRESAS TURISTICAS',
       'DIRECCION Y PRODUCCION DE CINE Y TELEVISION',

In [ ]:
columns = ['E_PRIVADO_LIBERTAD','E_PRGM_ACADEMICO']
train[columns]

       E_PRIVADO_LIBERTAD                                 E_PRGM_ACADEMICO
0                       N                                       ENFERMERIA
1                       N                                          DERECHO
2                       N                            MERCADEO Y PUBLICIDAD
3                       N                       ADMINISTRACION DE EMPRESAS
4                       N                                       PSICOLOGIA
...                   ...                                              ...
383884                  N                                   JURISPRUDENCIA
383885                  N                                   TRABAJO SOCIAL
383886                  N  INGENIERIA EN SEGURIDAD Y SALUD PARA EL TRABAJO
383887                  N                               CONTADURIA PUBLICA
383888                NaN                               CONTADURIA PUBLICA

[383889 rows x 2 columns]

In [ ]:
train['E_PRIVADO_LIBERTAD'].unique()

array(['N', 'S', nan], dtype=object)

In [ ]:
filtered_train = train[(train['E_PRIVADO_LIBERTAD'] == 'S') & (train['E_PRGM_ACADEMICO'] == 'DERECHO')]
filtered_train.head()

,ID,PERIODO_ACADEMICO,E_PRGM_ACADEMICO,E_PRGM_DEPARTAMENTO,E_VALORMATRICULAUNIVERSIDAD,E_HORASSEMANATRABAJA,F_ESTRATOVIVIENDA,F_TIENEINTERNET,F_EDUCACIONPADRE,F_TIENELAVADORA,...,E_PRIVADO_LIBERTAD,E_PAGOMATRICULAPROPIO,F_TIENECOMPUTADOR,F_TIENEINTERNET.1,F_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,INDICADOR_1,INDICADOR_2,INDICADOR_3,INDICADOR_4
8874,551725,20203,DERECHO,BOGOTÁ,NaN,NaN,NaN,NaN,NaN,NaN,...,S,NaN,NaN,NaN,NaN,medio-alto,0.028,0.035,0.041,0.034
64116,266662,20212,DERECHO,BOLIVAR,NaN,NaN,NaN,NaN,NaN,NaN,...,S,NaN,NaN,NaN,NaN,bajo,0.044,0.002,0.028,0.001
294234,491186,20212,DERECHO,BOLIVAR,NaN,NaN,NaN,NaN,NaN,NaN,...,S,NaN,NaN,NaN,NaN,bajo,0.008,0.031,0.031,0.003